# Generated by Django 3.0.3 on 2020-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201124_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='posts/files'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='posts/files'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic8.svg', upload_to='profile_pics'),
        ),
    ]
